// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: invoice/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetInvoiceRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetInvoiceRequest) Reset()         { *m = QueryGetInvoiceRequest{} }
func (m *QueryGetInvoiceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetInvoiceRequest) ProtoMessage()    {}
func (*QueryGetInvoiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42451b139c18b2f9, []int{0}
}
func (m *QueryGetInvoiceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetInvoiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetInvoiceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetInvoiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetInvoiceRequest.Merge(m, src)
}
func (m *QueryGetInvoiceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetInvoiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetInvoiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetInvoiceRequest proto.InternalMessageInfo

func (m *QueryGetInvoiceRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetInvoiceResponse struct {
	Invoice Invoice `protobuf:"bytes,1,opt,name=Invoice,proto3" json:"Invoice"`
}

func (m *QueryGetInvoiceResponse) Reset()         { *m = QueryGetInvoiceResponse{} }
func (m *QueryGetInvoiceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetInvoiceResponse) ProtoMessage()    {}
func (*QueryGetInvoiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42451b139c18b2f9, []int{1}
}
func (m *QueryGetInvoiceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetInvoiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetInvoiceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetInvoiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetInvoiceResponse.Merge(m, src)
}
func (m *QueryGetInvoiceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetInvoiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetInvoiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetInvoiceResponse proto.InternalMessageInfo

func (m *QueryGetInvoiceResponse) GetInvoice() Invoice {
	if m != nil {
		return m.Invoice
	}
	return Invoice{}
}

type QueryAllInvoiceRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllInvoiceRequest) Reset()         { *m = QueryAllInvoiceRequest{} }
func (m *QueryAllInvoiceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllInvoiceRequest) ProtoMessage()    {}
func (*QueryAllInvoiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42451b139c18b2f9, []int{2}
}
func (m *QueryAllInvoiceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllInvoiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllInvoiceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllInvoiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllInvoiceRequest.Merge(m, src)
}
func (m *QueryAllInvoiceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllInvoiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllInvoiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllInvoiceRequest proto.InternalMessageInfo

func (m *QueryAllInvoiceRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllInvoiceResponse struct {
	Invoice    []Invoice           `protobuf:"bytes,1,rep,name=Invoice,proto3" json:"Invoice"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllInvoiceResponse) Reset()         { *m = QueryAllInvoiceResponse{} }
func (m *QueryAllInvoiceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllInvoiceResponse) ProtoMessage()    {}
func (*QueryAllInvoiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42451b139c18b2f9, []int{3}
}
func (m *QueryAllInvoiceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllInvoiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllInvoiceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllInvoiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllInvoiceResponse.Merge(m, src)
}
func (m *QueryAllInvoiceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllInvoiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllInvoiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllInvoiceResponse proto.InternalMessageInfo

func (m *QueryAllInvoiceResponse) GetInvoice() []Invoice {
	if m != nil {
		return m.Invoice
	}
	return nil
}

func (m *QueryAllInvoiceResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetInvoiceRequest)(nil), "stateset.core.invoice.QueryGetInvoiceRequest")
	proto.RegisterType((*QueryGetInvoiceResponse)(nil), "stateset.core.invoice.QueryGetInvoiceResponse")
	proto.RegisterType((*QueryAllInvoiceRequest)(nil), "stateset.core.invoice.QueryAllInvoiceRequest")
	proto.RegisterType((*QueryAllInvoiceResponse)(nil), "stateset.core.invoice.QueryAllInvoiceResponse")
}

func init() { proto.RegisterFile("invoice/query.proto", fileDescriptor_42451b139c18b2f9) }

var fileDescriptor_42451b139c18b2f9 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x6a, 0xdb, 0x30,
	0x18, 0xc7, 0x2d, 0x2f, 0xdb, 0x40, 0x83, 0x1d, 0xb4, 0x65, 0x1b, 0x61, 0x68, 0xc1, 0x63, 0x59,
	0xd8, 0x98, 0x44, 0xb2, 0xfb, 0x20, 0x39, 0x2c, 0xf4, 0xd6, 0xfa, 0xd6, 0x9e, 0x2a, 0x3b, 0xc2,
	0x15, 0x38, 0x96, 0x13, 0x29, 0xa1, 0xa1, 0xf4, 0xd2, 0x27, 0x28, 0x84, 0xbe, 0x40, 0xdf, 0xa1,
	0xef, 0x90, 0x63, 0xa0, 0x97, 0x9e, 0x4a, 0x49, 0xfa, 0x20, 0xc5, 0xb6, 0x9c, 0xa6, 0x49, 0x9a,
	0xb6, 0x27, 0x8b, 0x8f, 0xff, 0xff, 0xff, 0xfd, 0xf4, 0x7d, 0x16, 0xfc, 0x20, 0xa2, 0x81, 0x14,
	0x3e, 0xa7, 0xdd, 0x3e, 0xef, 0x0d, 0x49, 0xdc, 0x93, 0x5a, 0xa2, 0xa2, 0xd2, 0x4c, 0x73, 0xc5,
	0x35, 0xf1, 0x65, 0x8f, 0x13, 0x23, 0x29, 0x7d, 0x0d, 0xa4, 0x0c, 0x42, 0x4e, 0x59, 0x2c, 0x28,
	0x8b, 0x22, 0xa9, 0x99, 0x16, 0x32, 0x52, 0x99, 0xa9, 0xf4, 0xcb, 0x97, 0xaa, 0x23, 0x15, 0xf5,
	0x98, 0x32, 0x69, 0x74, 0x50, 0xf3, 0xb8, 0x66, 0x35, 0x1a, 0xb3, 0x40, 0x44, 0xa9, 0xd8, 0x68,
	0x8b, 0x79, 0x57, 0xf3, 0x35, 0xe5, 0x8f, 0x81, 0x0c, 0x64, 0x7a, 0xa4, 0xc9, 0x29, 0xab, 0x3a,
	0x55, 0xf8, 0x69, 0x27, 0x89, 0x6b, 0x71, 0xbd, 0x95, 0xc9, 0x5d, 0xde, 0xed, 0x73, 0xa5, 0xd1,
	0x7b, 0x68, 0x8b, 0xf6, 0x17, 0x50, 0x06, 0xd5, 0x82, 0x6b, 0x8b, 0xb6, 0xb3, 0x0b, 0x3f, 0xaf,
	0x28, 0x55, 0x2c, 0x23, 0xc5, 0xd1, 0x3f, 0xf8, 0xd6, 0x94, 0x52, 0xfd, 0xbb, 0x3a, 0x26, 0x6b,
	0x2f, 0x49, 0x8c, 0xaa, 0x59, 0x18, 0x5f, 0x7f, 0xb3, 0xdc, 0xdc, 0xe4, 0xec, 0x1b, 0x88, 0x46,
	0x18, 0x2e, 0x41, 0xfc, 0x87, 0xf0, 0xfe, 0x7e, 0x26, 0xbc, 0x42, 0xb2, 0x61, 0x90, 0x64, 0x18,
	0x24, 0x1b, 0xad, 0x19, 0x06, 0xd9, 0x66, 0x41, 0xee, 0x75, 0x17, 0x9c, 0xce, 0x39, 0x30, 0xf4,
	0x8b, 0x2d, 0xd6, 0xd1, 0xbf, 0x7a, 0x31, 0x3d, 0x6a, 0x3d, 0x60, 0xb4, 0x53, 0xc6, 0x9f, 0x4f,
	0x32, 0x66, 0xcd, 0x17, 0x21, 0xeb, 0x17, 0x36, 0x7c, 0x9d, 0x42, 0xa2, 0x33, 0x30, 0x67, 0x42,
	0x7f, 0x1e, 0xa1, 0x59, 0xbf, 0xb6, 0x12, 0x79, 0xae, 0x3c, 0x03, 0x70, 0x7e, 0x9f, 0x5c, 0xde,
	0x8e, 0xec, 0x1f, 0xe8, 0x3b, 0xcd, 0x7d, 0x34, 0xf1, 0xd1, 0xa5, 0x9f, 0x88, 0x1e, 0x89, 0xf6,
	0x31, 0x1a, 0x01, 0x08, 0x4d, 0x40, 0x23, 0x0c, 0x37, 0xa3, 0xad, 0x2c, 0x73, 0x33, 0xda, 0xea,
	0x62, 0x9c, 0x4a, 0x8a, 0x56, 0x46, 0x78, 0x33, 0x5a, 0xb3, 0x39, 0x9e, 0x62, 0x30, 0x99, 0x62,
	0x70, 0x33, 0xc5, 0xe0, 0x74, 0x86, 0xad, 0xc9, 0x0c, 0x5b, 0x57, 0x33, 0x6c, 0xed, 0x55, 0x03,
	0xa1, 0x0f, 0xfa, 0x1e, 0xf1, 0x65, 0x67, 0x29, 0xe3, 0x70, 0x9e, 0xa2, 0x87, 0x31, 0x57, 0xde,
	0x9b, 0xf4, 0x39, 0xfc, 0xbd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x18, 0xbd, 0x32, 0x40, 0xb3, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a invoice by id.
	Invoice(ctx context.Context, in *QueryGetInvoiceRequest, opts ...grpc.CallOption) (*QueryGetInvoiceResponse, error)
	// Queries a list of invoice items.
	InvoiceAll(ctx context.Context, in *QueryAllInvoiceRequest, opts ...grpc.CallOption) (*QueryAllInvoiceResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Invoice(ctx context.Context, in *QueryGetInvoiceRequest, opts ...grpc.CallOption) (*QueryGetInvoiceResponse, error) {
	out := new(QueryGetInvoiceResponse)
	err := c.cc.Invoke(ctx, "/stateset.core.invoice.Query/Invoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) InvoiceAll(ctx context.Context, in *QueryAllInvoiceRequest, opts ...grpc.CallOption) (*QueryAllInvoiceResponse, error) {
	out := new(QueryAllInvoiceResponse)
	err := c.cc.Invoke(ctx, "/stateset.core.invoice.Query/InvoiceAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a invoice by id.
	Invoice(context.Context, *QueryGetInvoiceRequest) (*QueryGetInvoiceResponse, error)
	// Queries a list of invoice items.
	InvoiceAll(context.Context, *QueryAllInvoiceRequest) (*QueryAllInvoiceResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Invoice(ctx context.Context, req *QueryGetInvoiceRequest) (*QueryGetInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoice not implemented")
}
func (*UnimplementedQueryServer) InvoiceAll(ctx context.Context, req *QueryAllInvoiceRequest) (*QueryAllInvoiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvoiceAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Invoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Invoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stateset.core.invoice.Query/Invoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Invoice(ctx, req.(*QueryGetInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_InvoiceAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).InvoiceAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stateset.core.invoice.Query/InvoiceAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).InvoiceAll(ctx, req.(*QueryAllInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stateset.core.invoice.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoice",
			Handler:    _Query_Invoice_Handler,
		},
		{
			MethodName: "InvoiceAll",
			Handler:    _Query_InvoiceAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invoice/query.proto",
}

func (m *QueryGetInvoiceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetInvoiceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetInvoiceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetInvoiceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetInvoiceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetInvoiceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Invoice.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllInvoiceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllInvoiceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllInvoiceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllInvoiceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllInvoiceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllInvoiceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Invoice) > 0 {
		for iNdEx := len(m.Invoice) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Invoice[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetInvoiceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetInvoiceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Invoice.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllInvoiceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllInvoiceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Invoice) > 0 {
		for _, e := range m.Invoice {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetInvoiceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetInvoiceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetInvoiceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetInvoiceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetInvoiceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetInvoiceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invoice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Invoice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllInvoiceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllInvoiceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllInvoiceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllInvoiceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllInvoiceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllInvoiceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invoice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invoice = append(m.Invoice, Invoice{})
			if err := m.Invoice[len(m.Invoice)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
