package types

const (
	EventTypeMintSSUSD      = "mint_ssusd"
	EventTypeBurnSSUSD      = "burn_ssusd"
	EventTypeCreateAgent    = "create_agent"
	EventTypeAgentTransfer  = "agent_transfer"
	EventTypeLiquidation    = "liquidation"
	EventTypeAuctionBid     = "auction_bid"
	EventTypeOracleUpdate   = "oracle_update"
	EventTypeStabilityDeposit = "stability_deposit"
	EventTypeStabilityWithdraw = "stability_withdraw"
	
	AttributeKeyMinter            = "minter"
	AttributeKeyBurner            = "burner"
	AttributeKeyCollateral        = "collateral"
	AttributeKeyMinted            = "minted"
	AttributeKeyBurned            = "burned"
	AttributeKeyCollateralRatio   = "collateral_ratio"
	AttributeKeyCollateralReturned = "collateral_returned"
	AttributeKeyAgentID           = "agent_id"
	AttributeKeyOwner             = "owner"
	AttributeKeyWalletAddress     = "wallet_address"
	AttributeKeyFromAgent         = "from_agent"
	AttributeKeyToAgent           = "to_agent"
	AttributeKeyAmount            = "amount"
	AttributeKeyTransactionID     = "transaction_id"
	AttributeKeyMemo              = "memo"
	AttributeKeyLiquidator        = "liquidator"
	AttributeKeyDebtor            = "debtor"
	AttributeKeyAuctionID         = "auction_id"
	AttributeKeyDebt              = "debt"
	AttributeKeyBidder            = "bidder"
	AttributeKeyBidAmount         = "bid_amount"
	AttributeKeyOracle            = "oracle"
	AttributeKeyAsset             = "asset"
	AttributeKeyPrice             = "price"
	AttributeKeyDepositor         = "depositor"
	AttributeKeyWithdrawer        = "withdrawer"
	AttributeKeyRewards           = "rewards"
)