version: 1
build:
  binary: statesetd
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 2000000state
  - 200000000stake
- name: bob
  coins:
  - 1000000state
  - 100000000stake
- name: carol
  coins:
  - 1000000state
  - 100000000stake
- name: dom
  coins:
  - 1000000state
  - 100000000stake
- name: eve
  coins:
  - 1000000state
  - 100000000stake
faucet:
  name: bob
  coins:
  - 80000000state
  - 100000stake
  host: 0.0.0.0:4500
genesis:
  chain_id: stateset-1-testnet
validators:
- name: alice
  bonded: 100000000stake
