accounts:
  - name: alice
    coins: ["2000000state", "200000000stake"]
  - name: bob
    coins: ["1000000state", "100000000stake"]
  - name: carol
    coins: ["1000000state", "100000000stake"]
  - name: dom
    coins: ["1000000state", "100000000stake"]
  - name: eve
    coins: ["1000000state", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
faucet:
  name: bob
  coins: ["80000000state", "100000stake"]
build:
  binary: "statesetd"
genesis:
  chain_id: "stateset-1-testnet"
