version: '3.8'

services:
  stateset-node:
    build:
      context: .
      dockerfile: Dockerfile.stateset
    container_name: stateset-blockchain
    ports:
      - "26656:26656"  # P2P
      - "26657:26657"  # RPC
      - "1317:1317"    # REST API
      - "9090:9090"    # gRPC
      - "9091:9091"    # gRPC-Web
    environment:
      - DAEMON_NAME=statesetd
      - DAEMON_HOME=/root/.stateset
      - CHAIN_ID=stateset-1
    volumes:
      - ./stateset-data:/root/.stateset
    command: >
      sh -c "
        if [ ! -f /root/.stateset/config/genesis.json ]; then
          echo 'Initializing StateSet blockchain...'
          statesetd init stateset-node --chain-id stateset-1
          
          # Update staking denomination to stst
          sed -i 's/\"bond_denom\": \"stake\"/\"bond_denom\": \"stst\"/' /root/.stateset/config/genesis.json
          
          # Update mint denomination to stst
          sed -i 's/\"mint_denom\": \"stake\"/\"mint_denom\": \"stst\"/' /root/.stateset/config/genesis.json
          
          # Update crisis denomination to stst
          sed -i 's/\"denom\": \"stake\"/\"denom\": \"stst\"/g' /root/.stateset/config/genesis.json
          
          # Create validator key
          statesetd keys add validator --keyring-backend test
          
          # Get validator address
          VALIDATOR_ADDR=\$(statesetd keys show validator -a --keyring-backend test)
          echo \"Validator address: \$VALIDATOR_ADDR\"
          
          # Add genesis account with tokens
          statesetd genesis add-genesis-account \$VALIDATOR_ADDR 100000000000stst --keyring-backend test
          
          # Create genesis transaction
          statesetd genesis gentx validator 100000000stst --chain-id stateset-1 --keyring-backend test
          
          # Collect genesis transactions
          statesetd genesis collect-gentxs
          
          # Configure for development
          sed -i 's/minimum-gas-prices = \"\"/minimum-gas-prices = \"0.025stst\"/' /root/.stateset/config/app.toml
          sed -i 's/enable = false/enable = true/' /root/.stateset/config/app.toml
          sed -i 's/swagger = false/swagger = true/' /root/.stateset/config/app.toml
        fi
        
        echo 'Starting StateSet blockchain node...'
        statesetd start --api.enable --api.swagger
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:26657/status"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped