package types

// Event types for the STST module
const (
	EventTypeStakeTokens          = "stake_tokens"
	EventTypeUnstakeTokens        = "unstake_tokens"
	EventTypeWithdrawRewards      = "withdraw_rewards"
	EventTypeCreateValidator      = "create_validator"
	EventTypeEditValidator        = "edit_validator"
	EventTypeUnjailValidator      = "unjail_validator"
	EventTypeSlashValidator       = "slash_validator"
	EventTypeCompleteUnbonding    = "complete_unbonding"
	EventTypeCompleteRedelegation = "complete_redelegation"
	EventTypeBond                 = "bond"
	EventTypeUnbond               = "unbond"
	EventTypeRedelegate           = "redelegate"
	EventTypeSetWithdrawAddress   = "set_withdraw_address"
	EventTypeRewards              = "rewards"
	EventTypeCommission           = "commission"
	EventTypeSlash                = "slash"
	EventTypeLiveness             = "liveness"
	EventTypeMint                 = "mint"
	EventTypeBurn                 = "burn"
	EventTypeExecuteAgent         = "execute_agent"
	EventTypeAgentExecution       = "agent_execution"
	EventTypeFeeBurn              = "fee_burn"
	EventTypeTreasuryBurn         = "treasury_burn"
	EventTypeProtocolBuyback      = "protocol_buyback"
	EventTypeVestingRelease       = "vesting_release"
	EventTypeDAOVote              = "dao_vote"
	EventTypeParameterUpdate      = "parameter_update"
)

// Event attribute keys
const (
	AttributeKeyValidator         = "validator"
	AttributeKeyDelegator         = "delegator"
	AttributeKeyAmount            = "amount"
	AttributeKeyCompletionTime    = "completion_time"
	AttributeKeyCreationHeight    = "creation_height"
	AttributeKeyDestinationValidator = "destination_validator"
	AttributeKeySourceValidator   = "source_validator"
	AttributeKeyCommissionRate    = "commission_rate"
	AttributeKeyMinSelfDelegation = "min_self_delegation"
	AttributeKeySlashAmount       = "slash_amount"
	AttributeKeySlashFraction     = "slash_fraction"
	AttributeKeyInfractionHeight  = "infraction_height"
	AttributeKeyInfractionTime    = "infraction_time"
	AttributeKeyJailed            = "jailed"
	AttributeKeyReason            = "reason"
	AttributeKeyPower             = "power"
	AttributeKeyMissedBlocks      = "missed_blocks"
	AttributeKeyBondedRatio       = "bonded_ratio"
	AttributeKeyInflation         = "inflation"
	AttributeKeyProvisions        = "provisions"
	AttributeKeyTotalSupply       = "total_supply"
	AttributeKeyBondedTokens      = "bonded_tokens"
	AttributeKeyNotBondedTokens   = "not_bonded_tokens"
	
	// Agent and tokenomics attribute keys
	AttributeKeyAgentID           = "agent_id"
	AttributeKeyExecutor          = "executor"
	AttributeKeyExecutionResult   = "execution_result"
	AttributeKeyGasUsed           = "gas_used"
	AttributeKeyExecutionFee      = "execution_fee"
	AttributeKeyBurnedAmount      = "burned_amount"
	AttributeKeyBurnRate          = "burn_rate"
	AttributeKeyTreasuryAmount    = "treasury_amount"
	AttributeKeyVestingSchedule   = "vesting_schedule"
	AttributeKeyBuybackAmount     = "buyback_amount"
	AttributeKeyCirculatingSupply = "circulating_supply"
	AttributeKeyParameterName     = "parameter_name"
	AttributeKeyParameterValue    = "parameter_value"
	AttributeKeyProposalID        = "proposal_id"
	AttributeKeyVotingPower       = "voting_power"
	
	// Common attribute values
	AttributeValueCategory        = ModuleName
	AttributeValueAction         = "action"
	AttributeValueDoubleSign     = "double_sign"
	AttributeValueMissingSignature = "missing_signature"
	AttributeValueAgentExecution  = "agent_execution"
	AttributeValueFeeBurn         = "fee_burn"
	AttributeValueTreasuryBurn    = "treasury_burn"
	AttributeValueProtocolBuyback = "protocol_buyback"
)