package types

import errorsmod "cosmossdk.io/errors"

var (
	ErrUnsupportedCollateral   = errorsmod.Register(ModuleName, 1, "unsupported collateral")
	ErrVaultNotFound           = errorsmod.Register(ModuleName, 2, "vault not found")
	ErrInvalidVault            = errorsmod.Register(ModuleName, 3, "invalid vault parameters")
	ErrUnderCollateralized     = errorsmod.Register(ModuleName, 4, "vault below minimum collateral ratio")
	ErrUnauthorized            = errorsmod.Register(ModuleName, 5, "unauthorized")
	ErrInvalidAmount           = errorsmod.Register(ModuleName, 6, "invalid amount")
	ErrPriceNotFound           = errorsmod.Register(ModuleName, 7, "price not available")
	ErrPriceStale              = errorsmod.Register(ModuleName, 8, "price is stale")
	ErrLiquidationSurge        = errorsmod.Register(ModuleName, 9, "liquidation surge protection triggered")
	ErrVaultHealthy            = errorsmod.Register(ModuleName, 10, "vault is healthy, cannot liquidate")
	ErrInsufficientCollateral  = errorsmod.Register(ModuleName, 11, "insufficient collateral")
	ErrDebtLimitExceeded       = errorsmod.Register(ModuleName, 12, "debt limit exceeded")
	ErrCollateralInactive      = errorsmod.Register(ModuleName, 13, "collateral type is inactive")
	ErrComplianceCheckFailed   = errorsmod.Register(ModuleName, 14, "compliance check failed")
	ErrModuleAccountNotFound   = errorsmod.Register(ModuleName, 15, "module account not found")
	ErrInvalidCollateralParams = errorsmod.Register(ModuleName, 16, "invalid collateral parameters")
	ErrVaultMintingDisabled    = errorsmod.Register(ModuleName, 17, "vault minting is disabled")

	// Reserve-backed stablecoin errors
	ErrInvalidReserve           = errorsmod.Register(ModuleName, 20, "invalid reserve")
	ErrUnsupportedReserveAsset  = errorsmod.Register(ModuleName, 21, "unsupported reserve asset")
	ErrReserveDepositNotFound   = errorsmod.Register(ModuleName, 22, "reserve deposit not found")
	ErrRedemptionNotFound       = errorsmod.Register(ModuleName, 23, "redemption request not found")
	ErrInsufficientReserves     = errorsmod.Register(ModuleName, 24, "insufficient reserves")
	ErrReserveRatioBelowMinimum = errorsmod.Register(ModuleName, 25, "reserve ratio below minimum")
	ErrMintPaused               = errorsmod.Register(ModuleName, 26, "minting is paused")
	ErrRedeemPaused             = errorsmod.Register(ModuleName, 27, "redemption is paused")
	ErrDailyMintLimitExceeded   = errorsmod.Register(ModuleName, 28, "daily mint limit exceeded")
	ErrDailyRedeemLimitExceeded = errorsmod.Register(ModuleName, 29, "daily redeem limit exceeded")
	ErrBelowMinimumMint         = errorsmod.Register(ModuleName, 30, "below minimum mint amount")
	ErrBelowMinimumRedeem       = errorsmod.Register(ModuleName, 31, "below minimum redeem amount")
	ErrAllocationLimitExceeded  = errorsmod.Register(ModuleName, 32, "reserve asset allocation limit exceeded")
	ErrRedemptionNotReady       = errorsmod.Register(ModuleName, 33, "redemption not yet executable")
	ErrKYCRequired              = errorsmod.Register(ModuleName, 34, "KYC verification required")
	ErrInvalidAttester          = errorsmod.Register(ModuleName, 35, "invalid attester")
)
